version: "3"
services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    ports:
      - 8080:8080
      - 9901:9901
    command: ["-c", "/etc/front-envoy.yaml", "--service-cluster", "front-proxy"]
  opa-service:
    image: openpolicyagent/opa:latest-envoy
    volumes:
      - ./config.yaml:/work/config.yaml
      - ./opa.rego:/work/opa.rego
    command: ["run", "--server", "--log-level", "debug", "-c", "/work/config.yaml", "/work/opa.rego"]
     