apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-demo.fullname" . }}-config
data:
  front-envoy.yaml: |
    node:
      cluster: {{ .Values.envoyimage.node.cluster }}
      id: {{ .Values.envoyimage.node.id }}
    dynamic_resources:
      cds_config:
        path_config_source:
          {{ if .Values.envoyimage.persistentVolumeClaim }}
          path: /var/lib/envoy/{{ .Release.Name }}/config/cds/cds.yaml
          {{ else }}
          path: /var/lib/envoy/cds/cds.yaml
          {{ end }}
      lds_config:
        path_config_source:
          {{ if .Values.envoyimage.persistentVolumeClaim }}
          path: /var/lib/envoy/{{ .Release.Name }}/config/lds/lds.yaml
          {{ else }}
          path: /var/lib/envoy/lds/lds.yaml
          {{ end }}
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
