apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  front-envoy.yaml: |
    node:
      cluster: {{ .Values.envoyimage.node.cluster }}
      id: {{ .Values.envoyimage.node.id }}
    dynamic_resources:
      cds_config:
        path_config_source:
          path: /var/lib/envoy/cds/cds.yaml
      lds_config:
        path_config_source:
          path: /var/lib/envoy/lds/lds.yaml
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
