resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: en
    load_assignment:
      cluster_name: en
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8081
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: ja
    load_assignment:
      cluster_name: ja
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8082
