apiVersion: v1
kind: PersistentVolume
metadata:
  name: envoyproxy-examples-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: <Your Volume Id>

