apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envoy.fullname" . }}-secret
type: Opaque
stringData:
  token: {{ .Values.image.op.clientSecret }}
  hmac: {{ .Values.image.op.hmac }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "envoy.fullname" . }}-aws-credential
type: Opaque
stringData:
  aws_access_key_id: {{ .Values.image.s3.awsAccessKeyId }}
  aws_secret_access_key: {{ .Values.image.s3.awsSecretAccessKey }}
