name: build

on: [push]

jobs:
  push_to_registries:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
#      - name: configure aws credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#          aws-region: "ap-northeast-1"
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11.0.12'
          distribution: 'temurin'

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-s3
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}/front-proxy-s3

      - name: Extract metadata (tags, labels) for Docker
        id: meta-jwt
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}/front-proxy-jwt

      - name: Extract metadata (tags, labels) for Docker
        id: meta-opa
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}/front-proxy-opa

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: front-proxy-s3
          push: true
          tags: ${{ steps.meta-s3.outputs.tags }}
          labels: ${{ steps.meta-s3.outputs.labels }}

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: front-proxy-jwt
          push: true
          tags: ${{ steps.meta-jwt.outputs.tags }}
          labels: ${{ steps.meta-jwt.outputs.labels }}

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: front-proxy-opa
          push: true
          tags: ${{ steps.meta-opa.outputs.tags }}
          labels: ${{ steps.meta-opa.outputs.labels }}

      - run: (cd spring-boot; mvn spring-boot:build-image -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}/demo)
      - run: docker push "ghcr.io/${{ github.repository }}/demo:0.0.1-SNAPSHOT"
